POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username": "Adam",
    "email": "adam@gmail.com",
    "password": "adam123"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "fred@gmail.com",
    "password": "fred123"
}

###
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkZyZWQiLCJlbWFpbCI6ImZyZWRAZ21haWwuY29tIiwiaWF0IjoxNjc0NzIyMjc2LCJleHAiOjE2NzQ3MjIzMTZ9.YyvLAy_YZvbMKPelc7U7qASuwxbIA8AIShubdTIyZ0g

###
GET http://localhost:5000/api/auth/refresh_token